[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]   # Error, Formatting, Import rules
ignore = ["E501"]          # Ignore long line warnings

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
testpaths = ["."]
filterwarnings = [
    "ignore::DeprecationWarning",
]
